use enum_map::Enum;



#[derive(PartialEq, Eq, Clone, Copy, Debug, Enum)]
pub enum GuildAmenity {
    SignOfTheSilverFlameI,
    ShrineToTheDevouerI,
    StormreaverMemorialI,
    ShrineOfExperienceI,
    TheOrienExpress,
    ThreeFingerThads,
    FarshiftersChambers,
    Chronoscope,
    SellswordsTavern,
    BathHouse,
    FloatingRockGarden,
    ParadoxicalPuzzleBox,
    OldSullysGrogCellar,
    ThroneRoom,
    GuildStorageI,
    ShrineOfExperienceII,
    TacticalTrainingRoom,
    DangerRoom,
    ForbiddenLibrary,
    ArcheryRange,
    Armory,
    OttosIrrestableDancehall,
    CrusadersChapel,
    ArcaneSanctum,
    TrapsmithsWorkshop,
    ShrineOfExperienceIII,
    WildGrove,
    GrandmastersDojo,
    ProvingGround,
    CollegiumOfTheTwelve,
    BashtheBreakablesCargoBay,
    BlackAbbotsShadow,
    BanquetHall,
    ConcertHall,
    ArchWizard,
    GreenSteelCraftingHall,
    ShrineOfExperienceIV,
    CannithCraftingHall,
    GameHunter,
    FencingMaster,
    NinjaAssassin,
    HagApothecary,
    GuildStorageII,
    GrandReliquaryI,
    ShrineOfExperienceV,
    SignOfTheSilverFlameII,
    ShrineToTheDevouerII,
}
