#[derive(
    Debug,
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Hash,
    Clone,
    Copy,
    derive_more::Display,
    serde::Deserialize,
    serde::Serialize,
)]
pub enum Sheltering {
    Physical,
    Magical,
    MagicalCap,
    MagicalUncapped,
    PhysicalReduction,
    MagicalReduction,
}
