[package]
name = "app"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builder = { path = "../builder/" }
data = { path = "../data/" }
iced = "0.10.0"
roc = "0.0.0"

[[bin]]
name = "ddo-build-planner"
path = "src/main.rs"
