[package]
name = "app"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builder = { path = "../builder/"}
# iced = "0.9.0"
roc = "0.0.0"
enum-map = "2.5.0"
