[package]
name = "editor"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builder = { path = "../builder/", features = ["enum_map"]}
roc = "0.0.0"
serde = { version = "1.0.164" }
