[package]
name = "editor"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
keywords.workspace = true
license-file.workspace = true

[lints]
workspace = true

[dependencies]
builder = { path = "../builder/" }
roc = "0.0.0"
serde = { version = "1.0.192" }
iced = "0.10.0"

