[package]
name = "editor"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
keywords.workspace = true
license-file.workspace = true

[dependencies]
builder = { path = "../builder/", features = ["enum_map"]}
roc = "0.0.0"
serde = { version = "1.0.174" }
iced = "0.9"
iced_aw = "0.5.2"
