[package]
name = "builder"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true

[features]
enum_ord = ["dep:enum-map"]
enum_map = ["enum_ord"]
editor = ["enum_ord"]

[dependencies]
utils = { path = "../utils/" }
itertools = "0.11.0"
serde = { version = "1.0.188", features = ["derive"] }
ron = "0.8.1"
log = "0.4.20"
im = "15.1.0"
enum-map = {version = "2.6.2", features = ["serde"], optional = true}

[dev-dependencies]
builder = { path = ".", features = ["enum_ord"] }
serde_test = "1.0.176"
