[package]
name = "builder"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true


[profile.release]
lto = true
codegen-units = 1
panic = "abort"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = {version = "2.5.0", features = ["serde"]}
itertools = "0.10.5"
serde = { version = "1.0.164", features = ["derive"] }
ron = "0.8.0"
serde_test = "1.0.163"
log = "0.4.18"
im = "15.1.0"
# TODO: Change serde_test to dev-dependencies?

[dev-dependencies]
