[package]
name = "builder"
license-file.workspace = true
edition.workspace = true
version.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
description.workspace = true
categories.workspace = true
keywords.workspace = true

[features]
enum_ord = ["dep:enum-map"]
enum_map = ["enum_ord"]
editor = ["enum_ord"]
debug = ["utils/debug"]

[dependencies]
utils = { path = "../utils/" }
itertools = "0.11.0"
serde = { version = "1.0.189", features = ["derive"] }
ron = "0.8.1"
log = "0.4.20"
im = "15.1.0"
enum-map = { version = "2.7.0", features = ["serde"], optional = true }

[dev-dependencies]
builder = { path = ".", features = ["enum_ord", "debug"] }
serde_test = "1.0.176"
