name: Push

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "5 4 * * *"

jobs:
  install:
    name: Install from Git
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          cache: false
      - name: Install Builder
        run: cargo install --git https://www.github.com/LittleTealeaf/ddo-build-planner app --rev $GITHUB_SHA
